name: "Armbian Build CI"
on:
  schedule:
    - cron: '0 0 * * 2,5'

  workflow_dispatch:
    inputs:
    
      BRANCH:
        type: choice
        description: "Kernel branch to use for build"
        options:
        - edge
        - vendor
        - CNflysky
        default: 'vendor'
        
      DESKTOP:
        type: choice
        description: "Desktop environment selection"
        options:
        - minimal
        - server
        - gnome
        - budgie
        - cinnamon
        - i3-wm
        - kde-neon
        - kde-plasma
        - mate
        - xfce
        - xmonad
        default: 'server'

      ENABLE_EXTENSIONS:
        type: choice
        description: "Armbian extension packages"
        options: [ 'mesa-vpu', ' ' ]
        default: " "

      DOCKER:
        type: choice
        description: "Build type: yes = Docker, no = Actions"
        required: false
        options: [ 'yes', 'no' ]
        default: 'no'
      
      nightly:
        description: "Build type: yes = nightly, no = stable"
        required: false
        options: [ 'yes', 'no' ]
        type: choice
        default: 'no'

      ROOTFS:
        type: choice
        description: "Root filesystem type"
        options:
        - ext4
        - btrfs
        default: 'ext4'
          
env:
  TZ: Asia/Shanghai

jobs:
  Armbian:  
    runs-on: ubuntu-22.04  
    strategy:
      matrix:
        BOARD: [ lemonpi, som3588-cat]
        RELEASE: [ noble, oracular, plucky, bookworm, trixie]
      
    steps:
      - name: "Checkout Board Source"
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          clean: false
          path: custom
          
      - name: "Checkout Build System"
        uses: actions/checkout@main
        with:
          repository: armbian/build
          clean: false
          ref: main
          path: build
          
      - name: "Checkout OS Source"
        uses: actions/checkout@main
        with:
          repository: armbian/os
          fetch-depth: 0
          clean: false
          path: os
    
      - name: "Set Build Environment"
        shell: bash
        run: |
          ## update
          sudo apt-get update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* openjdk* mysql* php* mongodb* dotnet* moby* snapd* android* || true
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo -E  apt-get autoclean
          sudo -E apt-get clean
          sudo -E  apt-get autoremove

          ## Remove residual config packages
          dpkg --list | grep "^rc"
          dpkg --list | grep "^rc" | cut -d " " -f 3
          dpkg --list | grep "^rc" | cut -d " " -f 3 | xargs sudo dpkg --purge
          
          ## Set userspace decode options based on desktop selection
          if [[ "${{ inputs.DESKTOP }}" == "minimal" ]]; then
            echo "BUILD_DESKTOP="no"" >> $GITHUB_ENV
            echo "BUILD_MINIMAL="yes"" >> $GITHUB_ENV
          elif [[ "${{ inputs.DESKTOP }}" == "server" ]]; then
            echo "BUILD_DESKTOP="no"" >> $GITHUB_ENV
            echo "BUILD_MINIMAL="no"" >> $GITHUB_ENV
          else
            echo "BUILD_DESKTOP="yes"" >> $GITHUB_ENV
            echo "BUILD_MINIMAL="no"" >> $GITHUB_ENV
            echo "DESKTOP_ENVIRONMENT="${{ inputs.DESKTOP }}"" >> $GITHUB_ENV
            echo "DESKTOP_APPGROUPS_SELECTED="browsers"" >> $GITHUB_ENV
            echo "DESKTOP_ENVIRONMENT_CONFIG_NAME="config_base"" >> $GITHUB_ENV
          fi

          ## Set build version and date from upstream Armbian OS
          echo "CURRENT_YEAR_MONTH=$(date +'%Y%m')" >> $GITHUB_ENV
          echo "VERSIONOS=$(cat build/VERSION)" >> $GITHUB_ENV
          
          ## Set version override if provided
          #cat os/stable.json | jq '.version' | sed "s/\"//g" | sed 's/^/ARMBIAN_VERSION=/' >> $GITHUB_ENV
          [[ "${{ inputs.armbian_version }}" != '' ]] && echo "ARMBIAN_VERSION=${{ inputs.armbian_version }}" >> $GITHUB_ENV
         
          ## Copy user patches and board files into build directory
          mkdir -p  ./build/userpatches
          cp -rf ./custom/Addboard/* ./build
          cp -rf ./os/userpatches/* ./build/userpatches

          ## Insert CNflysky kernel configuration into rockchip-rk3588 family config
          sed -i '41r ./build/config/sources/families/CNflysky.txt' ./build/config/sources/families/rockchip-rk3588.conf
          
          ## Add board maintainer to CODEOWNERS file
          sed -i '75i config/boards/${{ inputs.BOARD }}.conf		@YANXIAOXIH' ./build/.github/CODEOWNERS

      - name: "Compile Armbian Image [ ${{ matrix.BOARD }} ${{ matrix.RELEASE }} ]"
        shell: bash
        run: |
          ## Enter build directory
          cd ./build
          ## Run Armbian build script with selected options
          ./compile.sh \
          BOARD="${{ matrix.BOARD }}" \
          BRANCH="${{ inputs.BRANCH }}" \
          RELEASE="${{ matrix.RELEASE }}" \
          KERNEL_CONFIGURE="no" \
          BUILD_DESKTOP="${{ env.BUILD_DESKTOP }}" \
          BUILD_MINIMAL="${{ env.BUILD_MINIMAL }}" \
          DESKTOP_ENVIRONMENT="${{ env.DESKTOP_ENVIRONMENT }}" \
          DESKTOP_APPGROUPS_SELECTED="${{ env.DESKTOP_APPGROUPS_SELECTED }}" \
          DESKTOP_ENVIRONMENT_CONFIG_NAME="${{ env.DESKTOP_ENVIRONMENT_CONFIG_NAME }}" \
          ENABLE_EXTENSIONS="${{ inputs.ENABLE_EXTENSIONS || ' '  }}" \
          BOARD_FIRMWARE_INSTALL="-full" \
          SHARE_LOG="yes" \
          BETA="${{ inputs.nightly }}" \
          PREFER_DOCKER="${{ inputs.DOCKER }}" \
          ROOTFS_TYPE="${{ inputs.ROOTFS }}" \
          EXPERT="yes" \
          VENDOR=Armbian \
          IMAGE_XZ_COMPRESSION_RATIO=8 \
          COMPRESS_OUTPUTIMAGE=sha,gpg,xz

      - name: "Generate GitHub Release Body"
        if: success()
        run: |
            # Generate HTML body for GitHub Release
            echo "
              <p align='center'>
              <a href='https://www.armbian.com'>
              <img src='https://github.com/armbian/build/blob/main/.github/armbian-logo.png?raw=true' width='150'></a></p>
              <h1 align=center>Armbian OS</h1>
              <p align=center>
              <a href='https://www.armbian.com'><img alt='Armbian Linux stable' src='https://img.shields.io/badge/dynamic/json?label=Armbian%20Linux%20current&query=CURRENT&color=f71000&cacheSeconds=600&style=for-the-badge&url=https%3A%2F%2Fgithub.com%2Farmbian%2Fscripts%2Freleases%2Fdownload%2Fstatus%2Frunners_capacity.json'></a>
              <a href='https://www.armbian.com'><img alt='Armbian Linux rolling' src='https://img.shields.io/badge/dynamic/json?label=Armbian%20Linux%20edge&query=EDGE&color=34be5b&cacheSeconds=600&style=for-the-badge&url=https%3A%2F%2Fgithub.com%2Farmbian%2Fscripts%2Freleases%2Fdownload%2Fstatus%2Frunners_capacity.json'></a>
              </p>
              <br>

              - Board: ${{ matrix.BOARD }} 
              - Kernel: ${{ inputs.BRANCH }} 
              - Redroid: Vendor 
              - Verification: sha256sum 

              Please note that Armbian Rolling Releases are not recommended for production environments, as these builds are not thoroughly tested. However, in most cases, they should work well. 

              <br>
              &nbsp;
              </p>" > body.html

      - name: "Upload Armbian Image to GitHub Release"
        uses: ncipollo/release-action@main
        if: success()
        with:
          tag: "Armbian_V${{ env.VERSIONOS }}"
          name: "Armbian_V${{ env.VERSIONOS }}"
          artifacts: "build/output/images/*"
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: "body.html"
