config:

  overlay-directories:
    - { source: "defconfig", target: "configs" } # copies all files in defconfig dir to the configs/ dir in the u-boot source tree
    - { source: "dt", target: "dts/upstream/src/arm64/rockchip" } # copies all files in dt dir to the arch/arm/dts dir in the u-boot source tree
